version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      -.:/app
    restart: always
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      -"5432:5432"
    volumes:
      -postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
