services:
  api:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"

  db:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.25"

  redis:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.20"
