"""Create ClickAnalytics table

Revision ID: f4f9a4d7067b
Revises: 74d2e5213fe1
Create Date: 2025-04-12 09:48:07.154951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f9a4d7067b'
down_revision: Union[str, None] = '74d2e5213fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_blocked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_analytics_id'), 'click_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_click_analytics_short_url'), 'click_analytics', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_analytics_short_url'), table_name='click_analytics')
    op.drop_index(op.f('ix_click_analytics_id'), table_name='click_analytics')
    op.drop_table('click_analytics')
    # ### end Alembic commands ###
